# __Topics: Numpy__

In [1]:
import numpy as np
import scipy
import scipy.stats

### __1. What is NumPy?__

- NumPy is the fundamental package for scientific computing in Python.
- It is a Python library that provides a multidimensional array object, various derived objects _(such as masked arrays and matrices)_ and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

#### __5. Write a Python program to calculate the base-2, natural, and base-10 logarithms of each element in the NumPy array arr = np.array([1, 2, 4, 10, 100]) using np.log2, np.log, and np.log10__

In [5]:
array = np.array([1,2,4,10,100])

- __np.log2__

In [6]:
np.log2(array)

array([0.        , 1.        , 2.        , 3.32192809, 6.64385619])

- __np.log__

In [7]:
np.log(array)

array([0.        , 0.69314718, 1.38629436, 2.30258509, 4.60517019])

- __np.log10__

In [8]:
np.log10(array)

array([0.        , 0.30103   , 0.60205999, 1.        , 2.        ])

### __33. Write a Python program to compute the determinant, covariance, and inverse of a matrix using NumPy.__

In [2]:
sample_matrix = np.arange(1,10).reshape(3,3)
print(f"Sample matrix to find Determinant, Covariance & Inverse is:\n{sample_matrix}")

Sample matrix to find Determinant, Covariance & Inverse is:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


- __33.1 Determinant:__

In [3]:
print(f"Determinant of Matrix is:\n{np.linalg.det(sample_matrix)}")

Determinant of Matrix is:
0.0


- __33.2 Covariance:__

In [4]:
print(f"Covariance of Matrix is:\n{np.cov(sample_matrix)}")

Covariance of Matrix is:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


- __33.3 Inverse:__

In [5]:
print(f"Inverse of Matrix is:\n{np.linalg.inv([[1,2,3],[4,10,6],[1,7,8]])}")

Inverse of Matrix is:
[[ 0.95   0.125 -0.45 ]
 [-0.65   0.125  0.15 ]
 [ 0.45  -0.125  0.05 ]]


### __34. Write a Python program to compute the mean, median, mode, standard deviation, and variance of a NumPy array__

In [6]:
np_array = list()
for x in np.nditer(sample_matrix):
    np_array.append(x.tolist())

print(f"Sample NumPy Array:\n{np.array(np_array)}")

Sample NumPy Array:
[1 2 3 4 5 6 7 8 9]


- __34.1 mean():__

In [7]:
print(f"Mean of NumPy Array is:\n{np.mean(np_array)}")

Mean of NumPy Array is:
5.0


- __34.2 median():__

In [8]:
print(f"Meadian of NumPy Array is:\n{np.median(np_array)}")

Meadian of NumPy Array is:
5.0


- __34.3 mode():__

In [9]:
print(f"Meadian of NumPy Array is:\n{scipy.stats.mode(sample_matrix)[0]}")

Meadian of NumPy Array is:
[1 2 3]


- __34.4 Standard Deviation _np.std()_:__

In [10]:
print(f"Standard Deviation of NumPy Array is:\n{np.std(np_array)}")

Standard Deviation of NumPy Array is:
2.581988897471611


- __34.5 Variance _np.var()_:__

In [11]:
print(f"Varianec of NumPy Array is:\n{np.var(np_array)}")

Varianec of NumPy Array is:
6.666666666666667


### __35. Write a Python program to convert a 1D array to a 3D array and a 4D array to a 2D array using NumPy.__

In [12]:
original_1d_array = f"# STEP-1:\nOriginal 1D Array is:\n{np_array}\n"

#### __1D to 3D__

_Approach 1_

In [13]:
print(original_1d_array)
print(f"# STEP-2:\nCoverting this to 3D Array:\n{np.array([np.reshape(np_array, [3,3])])}")

# STEP-1:
Original 1D Array is:
[1, 2, 3, 4, 5, 6, 7, 8, 9]

# STEP-2:
Coverting this to 3D Array:
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


_Approach 2_

In [14]:
print(original_1d_array)
print(f"# STEP-2:\nCoverting this to 3D Array:\n{np.array(np_array).reshape(1, 3, 3)}")

# STEP-1:
Original 1D Array is:
[1, 2, 3, 4, 5, 6, 7, 8, 9]

# STEP-2:
Coverting this to 3D Array:
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


#### __4D to 2D__

In [15]:
print(original_1d_array)
d4_array = np.array([[np.reshape(np_array, [3,3])]])
print(f"# STEP-2:\nCreating 4D Array from Original:\n{d4_array}\n")
print(f"# STEP-3:\nCoverting this 4D Array to 2D Array:\n{np.reshape(d4_array, [3,3])}")

# STEP-1:
Original 1D Array is:
[1, 2, 3, 4, 5, 6, 7, 8, 9]

# STEP-2:
Creating 4D Array from Original:
[[[[1 2 3]
   [4 5 6]
   [7 8 9]]]]

# STEP-3:
Coverting this 4D Array to 2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### __36. Write a Python program to calculate the eigenvalues and eigenvectors of the matrix [[4, 1], [2, 3]] using NumPy__

In [16]:
sample_matrix = [[4,1],[2,3]]

eigenvalues, eigenvectors = np.linalg.eig(sample_matrix)
print(f"1. Eigenvalues of given matrix is:\n{eigenvalues}\n\n2. Eigenvectors of given matrix is:\n{eigenvectors}")

1. Eigenvalues of given matrix is:
[5. 2.]

2. Eigenvectors of given matrix is:
[[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]


### __37. Use the np.eye() function to create a 4x4 identity matrix and demonstrate how to multiply it by another 4x4 matrix filled with random numbers using NumPy.__

- __Creating 4x4 Identity & Another Matrix with Random Numbers:__

In [17]:
identity = np.eye(4,4, dtype=int)
print(f"Identity Matrix is:\n{identity}\n")

another = np.random.randint(1,25, [4,4])
print(f"Another Matrix with Random Numbers:\n{another}")

Identity Matrix is:
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]

Another Matrix with Random Numbers:
[[11  8 19 17]
 [12  5 14 14]
 [ 3 22 16  8]
 [21  2 13 19]]


- __Multiplying Identity Matrix with Another Matrix:__

In [18]:
print(f"Final Outcome is:\n{identity*another}")

Final Outcome is:
[[11  0  0  0]
 [ 0  5  0  0]
 [ 0  0 16  0]
 [ 0  0  0 19]]


### __38. Given two arrays A = np.array([1, 2, 3, 4, 5]) and B = np.array([4, 5, 6, 7, 8]), write a Python program to find their union and intersection using NumPy__

In [19]:
A = np.array([1, 2, 3, 4, 5])
B = np.array([4, 5, 6, 7, 8])

- __38.1 Union__

In [20]:
print(f"Union of Given Arrays:\n{np.union1d(A,B)}")

Union of Given Arrays:
[1 2 3 4 5 6 7 8]


- __38.2 Intersection__

In [21]:
print(f"Intersection of Given Arrays:\n{np.intersect1d(A,B)}")

Intersection of Given Arrays:
[4 5]


### __39. Create two sets from arrays and demonstrate how to perform the set difference between them using NumPy.__

- __39.1 Creating 2 Sets From Arrays:__

In [22]:
array = np.random.randint(0,5,10).reshape(2,5)
set1, set2 = array[0], array[1]

- __39.2 Created Sets:__

In [23]:
print(f"Set-1: {set1}\nSet-2: {set2}")

Set-1: [1 4 1 0 0]
Set-2: [4 1 3 3 0]


- __39.3 Difference between Set-1 & Set-2:__

In [24]:
print(f"Difference between Set1 & Set2 is:\n{np.setdiff1d(set1,set2)}")

Difference between Set1 & Set2 is:
[]


### __40. Given the polynomial equation P(x)=4x^2+6x−24, write a Python program to use NumPy to find the roots of this equation.__

- __40.1 Equation__

In [25]:
equation = [-24, 6, 4]
np.polynomial.Polynomial(equation)

Polynomial([-24.,   6.,   4.], domain=[-1.,  1.], window=[-1.,  1.], symbol='x')

- __40.2 Finding Roots__

_Approach 1_

In [26]:
print(f"Roots of above Equation is:\n{np.polynomial.Polynomial(equation).roots()}")

Roots of above Equation is:
[-3.31173769  1.81173769]


_Approach 2_

In [27]:
print(f"Roots of above Equation is:\n{np.polynomial.Polynomial.roots(np.polynomial.Polynomial(equation))}")

Roots of above Equation is:
[-3.31173769  1.81173769]
