# __Topics: NumPy__

In [1]:
import numpy as np
import scipy

### __1. What is NumPy?__

- NumPy is the fundamental package for scientific computing in Python.
- It is a Python library that provides a multidimensional array object, various derived objects _(such as masked arrays and matrices)_ and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

### __2. What are the key features of NumPy?__

__1. Multidimentionl Array:__ It can handle n-dimentional arrays easily.

__2. Speed of computation:__ It's implemantation done in C which provides substantian speed.

__3. Homogeneity:__ All elements would be in same data-type which ensures the faster operations.

__4. Vectorized Operations:__ operations can be applied to entire array at once without iterations.

### __3. Explain the difference between a Python list and a NumPy array.__

| Python List                                                                                | NumPy Array (`ndarray`)                                                                                            |
| ------------------------------------------------------------------------------------------ | -------------------------------------------------------------------------------------------------------------------- |
| Slower for numerical computations                                                          | Significantly faster for mathematical operations                                                                     |
| Less memory efficient due to storing type and reference information for each element.      | More memory efficient because all elements are the same type and are stored in a single, contiguous block of memory. |
| Standard built-in operations but lacks specialized functions for advanced numerical tasks. | Comes with a wide range of optimized mathematical functions, including linear algebra, Fourier transforms and more. |
| Offers flexible methods like `append()`, `insert()` & `remove()`.                 | Supports more advanced features like vectorized operations                                                           |
| Dynamic size; can grow or shrink as elements are added or removed.                         | Fixed size at creation; changing its size creates a new array.                                                       |

### __4. Explain the concept of indexing and slicing in NumPy.__

##### __4.1. Indexing:__
- to access specific element.

In [2]:
array = np.array([1,2,3,4,5])
array[0], array[2]

(np.int64(1), np.int64(3))

##### __4.2. Slicing:__
- to access specific range.

In [3]:
array[2:4], array[-3::-1]

(array([3, 4]), array([3, 2, 1]))

#### __5. Write a Python program to calculate the base-2, natural, and base-10 logarithms of each element in the NumPy array arr = np.array([1, 2, 4, 10, 100]) using np.log2, np.log, and np.log10__

In [4]:
array = np.array([1,2,4,10,100])

- __np.log2__

In [5]:
np.log2(array)

array([0.        , 1.        , 2.        , 3.32192809, 6.64385619])

- __np.log__

In [6]:
np.log(array)

array([0.        , 0.69314718, 1.38629436, 2.30258509, 4.60517019])

- __np.log10__

In [7]:
np.log10(array)

array([0.        , 0.30103   , 0.60205999, 1.        , 2.        ])

### __6. What is the equivalent of enumerate for NumPy arrays?__

iterating arrays with indices in numpy we can use _np.ndenumerate()_.

E.g:

In [8]:
for i, x in np.ndenumerate(array):
    print(f"Indice: {i} & Array: {x}")

Indice: (0,) & Array: 1
Indice: (1,) & Array: 2
Indice: (2,) & Array: 4
Indice: (3,) & Array: 10
Indice: (4,) & Array: 100


### __7. Write a Python program to create a null vector of size 10 using NumPy.__

In [9]:
np.zeros(10), f"Shape: {np.zeros(10).shape[0]}"

(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]), 'Shape: 10')

### __8. Write a Python program to find the number of rows and columns of a given matrix using NumPy.__

In [10]:
array1 = np.random.randint(1,10, [3,4])
f"Row: {array1.shape[0]}, Column: {array1.shape[1]}"

'Row: 3, Column: 4'

### __9. Write a Python program to reverse the order of elements in a given NumPy array.__

In [11]:
array, f"Reversed: {array[::-1]}"

(array([  1,   2,   4,  10, 100]), 'Reversed: [100  10   4   2   1]')

### __10. Write a Python program to create a NumPy array with values ranging from 15 to 30 and calculate the mean of the array.__

In [12]:
f"Mean of 15 to 30 is: {np.arange(15, 30).mean()}"

'Mean of 15 to 30 is: 22.0'

### __11. Given a NumPy array arr = np.array([2, 4, 6, 8, 10]), write a Python program to find out the square and cube of each element.__

In [13]:
arr = np.array([2, 4, 6, 8, 10])
f"Square: {arr ** 2}, Cube: {arr ** 2}"

'Square: [  4  16  36  64 100], Cube: [  4  16  36  64 100]'

### __12. Write a Python program to find indices of non-zero elements from [1,2,0,0,4,0] using NumPy.__

In [14]:
array2 = np.array([1,2,0,0,4,0])
f"non-zero element indices: {np.where(array2 != 0)[0]}"

'non-zero element indices: [0 1 4]'

### __13. Write a Python program to create a 3x3 matrix with values ranging from 0 to 8 using NumPy__

In [15]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### __14. Write a Python program to create a random vector of size 30 and find the mean value using NumPy.__

In [16]:
f"Random Vector Size of 30 Mean: {np.random.randint(1,31, 30).mean():.2f}"

'Random Vector Size of 30 Mean: 15.43'

### __15. Write a Python program to create a 3x3 identity matrix using np.eye and np.identity functions.__

In [17]:
print(f"1. With np.eye():\n{np.eye(3,3)},\n\n2. With np.identity():\n{np.identity(3)}")

1. With np.eye():
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]],

2. With np.identity():
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


### __16. Write a Python program to find common values between two arrays using NumPy.__

In [18]:
arr1 = np.random.randint(1,20, 10)
arr2 = np.random.randint(5,15, 10)

In [19]:
print(f"Array 1: {arr1}\nArray 2: {arr2}")

Array 1: [14 18 10  7 16 18  9 17 11  1]
Array 2: [ 9  7  9  9  5 11  7  6  7  5]


_Approach 1_

In [20]:
f"Common values: {np.intersect1d(arr1, arr2)}"

'Common values: [ 7  9 11]'

_Approach 2_

In [21]:
common_values = []
for x in arr1:
    for y in arr2:
        if x == y and x not in common_values:
            common_values.append(x)
        else:
            continue
print(f"Common Values: {[int(i) for i in sorted(common_values)]}")

Common Values: [7, 9, 11]


### __17. Write a Python program to create a random vector of size 10 and sort it in ascending and descending order using NumPy.__

In [22]:
print(f"Array      : {arr1}\nAscending  : {np.sort(arr1)}\nDescending : {arr1[::-1]}")

Array      : [14 18 10  7 16 18  9 17 11  1]
Ascending  : [ 1  7  9 10 11 14 16 17 18 18]
Descending : [ 1 11 17  9 18 16  7 10 18 14]


### __18. Consider two random arrays A and B. Write a Python program to check if they are equal using NumPy.__

In [23]:
np.array_equal(arr1, arr2)

False

### __19. Write a Python program to create a random vector of size 10 and replace the maximum value by 0 using NumPy.__

In [24]:
np.where(arr1 == arr1.max(), 0, arr1)

array([14,  0, 10,  7, 16,  0,  9, 17, 11,  1], dtype=int32)

### __20. Write a Python program to create a 5x5 matrix with row values ranging from 0 to 4 using NumPy.__

_Approach 1_

In [25]:
values = np.arange(5)
np.matrix([values]*len(values))

matrix([[0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4],
        [0, 1, 2, 3, 4]])

_Approach 2_

In [26]:
np.tile(values, [5,1])

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

### __21. Write a Python program to find the memory size of an array using NumPy.__

In [27]:
arr1.itemsize

4

### __22. Given two NumPy 2D arrays, write a Python program to concatenate them horizontally.__

In [28]:
array2d_1 = np.random.randint(1,10, [3,4])
array2d_2 = np.random.randint(1,10, [3,4])

In [29]:
array2d_1, array2d_2

(array([[7, 1, 5, 6],
        [8, 6, 5, 5],
        [9, 5, 1, 3]], dtype=int32),
 array([[1, 6, 6, 5],
        [5, 7, 6, 9],
        [5, 9, 7, 5]], dtype=int32))

- __Concatenating them horizontally:__

In [30]:
np.concatenate([array2d_1, array2d_2], axis=1)

array([[7, 1, 5, 6, 1, 6, 6, 5],
       [8, 6, 5, 5, 5, 7, 6, 9],
       [9, 5, 1, 3, 5, 9, 7, 5]], dtype=int32)

### __23. Write a NumPy program to add, subtract, multiply, and divide arguments element-wise.__

- __Addition:__

In [31]:
arr1 + arr2

array([23, 25, 19, 16, 21, 29, 16, 23, 18,  6], dtype=int32)

- __Subtraction:__

In [32]:
arr1 - arr2

array([ 5, 11,  1, -2, 11,  7,  2, 11,  4, -4], dtype=int32)

- __Multiply:__

In [33]:
arr1 * arr2

array([126, 126,  90,  63,  80, 198,  63, 102,  77,   5], dtype=int32)

- __Divide:__

In [34]:
arr1 / arr2

array([1.55555556, 2.57142857, 1.11111111, 0.77777778, 3.2       ,
       1.63636364, 1.28571429, 2.83333333, 1.57142857, 0.2       ])

### __24. Write a Python program to round elements of a NumPy array to the nearest integer.__

In [35]:
div = arr1 / arr2
div, np.around(div)

(array([1.55555556, 2.57142857, 1.11111111, 0.77777778, 3.2       ,
        1.63636364, 1.28571429, 2.83333333, 1.57142857, 0.2       ]),
 array([2., 3., 1., 1., 3., 2., 1., 3., 2., 0.]))

### __25. Write a Python program to get the floor and ceiling values of the elements of a NumPy array.__

In [36]:
print(f"Values : {div.tolist()[:3:]}\nFloor  : {np.floor(div)[:3:]}\nCeil   : {np.ceil(div)[:3:]}")

Values : [1.5555555555555556, 2.5714285714285716, 1.1111111111111112]
Floor  : [1. 2. 1.]
Ceil   : [2. 3. 2.]


### __26. Write a NumPy program to convert angles from degrees to radians for all elements in a given array.__

In [37]:
arr1, np.deg2rad(arr1)

(array([14, 18, 10,  7, 16, 18,  9, 17, 11,  1], dtype=int32),
 array([0.2443461 , 0.31415927, 0.17453293, 0.12217305, 0.27925268,
        0.31415927, 0.15707963, 0.29670597, 0.19198622, 0.01745329]))

### __27. Write a Python program to create a 10x10 array with random values and find the minimum and maximum values using NumPy.__

In [38]:
arr3 = np.random.random([10,10])
print(f"Minimun: {arr3.min()} | Maximun: {arr3.max()}")

Minimun: 0.007978187933922132 | Maximun: 0.9902599838637377


### __28. Write a NumPy program to create a 5x5 zero matrix with elements on the main diagonal equal to 1, 2, 3, 4, 5.__

In [39]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

### __29. Write a Python program to find out the dot product of a 5x3 and 3x2 matrix using NumPy.__

In [40]:
mat1 = np.random.randint(1,10, [5,3])
mat2 = np.random.randint(1,10, [3,2])

In [41]:
mat1, mat2

(array([[6, 2, 8],
        [9, 6, 1],
        [2, 2, 6],
        [2, 9, 9],
        [6, 3, 3]], dtype=int32),
 array([[1, 8],
        [4, 2],
        [8, 9]], dtype=int32))

- __Dot Product:__

In [42]:
np.dot(mat1, mat2)

array([[ 78, 124],
       [ 41,  93],
       [ 58,  74],
       [110, 115],
       [ 42,  81]], dtype=int32)

### __30. Given a 1D array, write a Python program to negate all elements which are between 3 and 8, in place, using NumPy.__

In [43]:
arr1

array([14, 18, 10,  7, 16, 18,  9, 17, 11,  1], dtype=int32)

In [44]:
print(f"Array: {arr1}\nNegate between 3 & 8: {np.where((arr1 > 3) & (arr1 < 8), -arr1, arr1)}")

Array: [14 18 10  7 16 18  9 17 11  1]
Negate between 3 & 8: [14 18 10 -7 16 18  9 17 11  1]


### __31. Write a Python program to extract all numbers between a given range from a NumPy array.__

In [45]:
print(f"Array: {arr1}\nRange 7 to 14: {arr1[arr1 == np.clip(arr1, 7,14)]}")

Array: [14 18 10  7 16 18  9 17 11  1]
Range 7 to 14: [14 10  7  9 11]


### __32. Write a Python program to create a 3x3x3 array with random values using NumPy.__

In [46]:
print(f"Array is:\n{np.array(range(1,28)).reshape(3,3,3)}\n\nShape: {np.array(range(1,28)).reshape(3,3,3).shape}")

Array is:
[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]

Shape: (3, 3, 3)


### __33. Write a Python program to compute the determinant, covariance, and inverse of a matrix using NumPy.__

In [47]:
sample_matrix = np.arange(1,10).reshape(3,3)
print(f"Sample matrix to find Determinant, Covariance & Inverse is:\n{sample_matrix}")

Sample matrix to find Determinant, Covariance & Inverse is:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


- __33.1 Determinant:__

In [48]:
print(f"Determinant of Matrix is:\n{np.linalg.det(sample_matrix)}")

Determinant of Matrix is:
0.0


- __33.2 Covariance:__

In [49]:
print(f"Covariance of Matrix is:\n{np.cov(sample_matrix)}")

Covariance of Matrix is:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


- __33.3 Inverse:__

In [50]:
print(f"Inverse of Matrix is:\n{np.linalg.inv([[1,2,3],[4,10,6],[1,7,8]])}")

Inverse of Matrix is:
[[ 0.95   0.125 -0.45 ]
 [-0.65   0.125  0.15 ]
 [ 0.45  -0.125  0.05 ]]


### __34. Write a Python program to compute the mean, median, mode, standard deviation, and variance of a NumPy array__

In [51]:
np_array = list()
for x in np.nditer(sample_matrix):
    np_array.append(x.tolist())

print(f"Sample NumPy Array:\n{np.array(np_array)}")

Sample NumPy Array:
[1 2 3 4 5 6 7 8 9]


- __34.1 mean():__

In [52]:
print(f"Mean of NumPy Array is:\n{np.mean(np_array)}")

Mean of NumPy Array is:
5.0


- __34.2 median():__

In [53]:
print(f"Meadian of NumPy Array is:\n{np.median(np_array)}")

Meadian of NumPy Array is:
5.0


- __34.3 mode():__

In [54]:
print(f"Meadian of NumPy Array is:\n{scipy.stats.mode(sample_matrix)[0]}")

Meadian of NumPy Array is:
[1 2 3]


- __34.4 Standard Deviation _np.std()_:__

In [55]:
print(f"Standard Deviation of NumPy Array is:\n{np.std(np_array)}")

Standard Deviation of NumPy Array is:
2.581988897471611


- __34.5 Variance _np.var()_:__

In [56]:
print(f"Varianec of NumPy Array is:\n{np.var(np_array)}")

Varianec of NumPy Array is:
6.666666666666667


### __35. Write a Python program to convert a 1D array to a 3D array and a 4D array to a 2D array using NumPy.__

In [57]:
original_1d_array = f"# STEP-1:\nOriginal 1D Array is:\n{np_array}\n"

#### __1D to 3D__

_Approach 1_

In [58]:
print(original_1d_array)
print(f"# STEP-2:\nCoverting this to 3D Array:\n{np.array([np.reshape(np_array, [3,3])])}")

# STEP-1:
Original 1D Array is:
[1, 2, 3, 4, 5, 6, 7, 8, 9]

# STEP-2:
Coverting this to 3D Array:
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


_Approach 2_

In [59]:
print(original_1d_array)
print(f"# STEP-2:\nCoverting this to 3D Array:\n{np.array(np_array).reshape(1, 3, 3)}")

# STEP-1:
Original 1D Array is:
[1, 2, 3, 4, 5, 6, 7, 8, 9]

# STEP-2:
Coverting this to 3D Array:
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


#### __4D to 2D__

In [60]:
print(original_1d_array)
d4_array = np.array([[np.reshape(np_array, [3,3])]])
print(f"# STEP-2:\nCreating 4D Array from Original:\n{d4_array}\n")
print(f"# STEP-3:\nCoverting this 4D Array to 2D Array:\n{np.reshape(d4_array, [3,3])}")

# STEP-1:
Original 1D Array is:
[1, 2, 3, 4, 5, 6, 7, 8, 9]

# STEP-2:
Creating 4D Array from Original:
[[[[1 2 3]
   [4 5 6]
   [7 8 9]]]]

# STEP-3:
Coverting this 4D Array to 2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### __36. Write a Python program to calculate the eigenvalues and eigenvectors of the matrix [[4, 1], [2, 3]] using NumPy__

In [61]:
sample_matrix = [[4,1],[2,3]]

eigenvalues, eigenvectors = np.linalg.eig(sample_matrix)
print(f"1. Eigenvalues of given matrix is:\n{eigenvalues}\n\n2. Eigenvectors of given matrix is:\n{eigenvectors}")

1. Eigenvalues of given matrix is:
[5. 2.]

2. Eigenvectors of given matrix is:
[[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]


### __37. Use the np.eye() function to create a 4x4 identity matrix and demonstrate how to multiply it by another 4x4 matrix filled with random numbers using NumPy.__

- __Creating 4x4 Identity & Another Matrix with Random Numbers:__

In [62]:
identity = np.eye(4,4, dtype=int)
print(f"Identity Matrix is:\n{identity}\n")

another = np.random.randint(1,25, [4,4])
print(f"Another Matrix with Random Numbers:\n{another}")

Identity Matrix is:
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]

Another Matrix with Random Numbers:
[[ 7 12 15 22]
 [11 21  1 24]
 [10 18  7 15]
 [22 16  6 22]]


- __Multiplying Identity Matrix with Another Matrix:__

In [63]:
print(f"Final Outcome is:\n{identity*another}")

Final Outcome is:
[[ 7  0  0  0]
 [ 0 21  0  0]
 [ 0  0  7  0]
 [ 0  0  0 22]]


### __38. Given two arrays A = np.array([1, 2, 3, 4, 5]) and B = np.array([4, 5, 6, 7, 8]), write a Python program to find their union and intersection using NumPy__

In [64]:
A = np.array([1, 2, 3, 4, 5])
B = np.array([4, 5, 6, 7, 8])

- __38.1 Union__

In [65]:
print(f"Union of Given Arrays:\n{np.union1d(A,B)}")

Union of Given Arrays:
[1 2 3 4 5 6 7 8]


- __38.2 Intersection__

In [66]:
print(f"Intersection of Given Arrays:\n{np.intersect1d(A,B)}")

Intersection of Given Arrays:
[4 5]


### __39. Create two sets from arrays and demonstrate how to perform the set difference between them using NumPy.__

- __39.1 Creating 2 Sets From Arrays:__

In [67]:
array = np.random.randint(0,5,10).reshape(2,5)
set1, set2 = array[0], array[1]

- __39.2 Created Sets:__

In [68]:
print(f"Set-1: {set1}\nSet-2: {set2}")

Set-1: [4 3 4 3 3]
Set-2: [0 2 3 0 2]


- __39.3 Difference between Set-1 & Set-2:__

In [69]:
print(f"Difference between Set1 & Set2 is:\n{np.setdiff1d(set1,set2)}")

Difference between Set1 & Set2 is:
[4]


### __40. Given the polynomial equation P(x)=4x^2+6x−24, write a Python program to use NumPy to find the roots of this equation.__

- __40.1 Equation__

In [70]:
equation = [-24, 6, 4]
np.polynomial.Polynomial(equation)

Polynomial([-24.,   6.,   4.], domain=[-1.,  1.], window=[-1.,  1.], symbol='x')

- __40.2 Finding Roots__

_Approach 1_

In [71]:
print(f"Roots of above Equation is:\n{np.polynomial.Polynomial(equation).roots()}")

Roots of above Equation is:
[-3.31173769  1.81173769]


_Approach 2_

In [72]:
print(f"Roots of above Equation is:\n{np.polynomial.Polynomial.roots(np.polynomial.Polynomial(equation))}")

Roots of above Equation is:
[-3.31173769  1.81173769]
