# __NumPy__

#### __1. Introduction__

NumPy stands for __Numerical Python__ which is a Python library used to work with arrays.

All Data Science algorithms (ML, DL, NLP, GenAI, Agentic AI, etc.) ultimately require input data to be in numerical form.
Non-numeric data like text, images, or audio is first transformed into numerical representations before being processed by algorithms

#### __2. Installation & Import__

```
pip install numpy
import numpy as np
```

In [1]:
import numpy as np

#### __3. Features__

__i) Homogeneous Datatypes:__
- All elements in a NumPy array are of the same type, ensuring faster operations.

__ii) High Performance:__
- Written in C(partially in python), NumPy executes much faster than Python lists.

__iii) Memory Efficient:__
- NumPy arrays take less space because data is stored together in one continuous block of memory

__iv) Multidimensional Support:__
- Can handle 1D, 2D, 3D, and higher-dimensional arrays easily.

__v) Rich Mathematical Functions:__
- Provides built-in functions for statistics, algebra, broadcasting and random number generation.

#### __4. Use cases:__

1. Linear Algebra(Metrix, Polynomial, ALgebric equations, etc)
2. Statistics(mean, median, mode, std, var, etc)
3. Trigonometry(sin,cos, tac, rad, deg,etc)
4. Logarithmic(log2, log, log10, etc)
5. Image Processing and CV
6. All Numerical calculations

# __Functions - I__

## __1. np.array__

A _np.array_ refers to an N-dimensional array, the fundamental data structure in the NumPy library for Python.

In [2]:
np.array([],dtype = int, ndmin = 2)

array([], shape=(1, 0), dtype=int64)

## __2. np.ndim__

_ndim_ is an attribute of a NumPy array _(ndarray)_ that returns the number of dimensions (axes) of the array.

In [3]:
new_list = [[15,5,3,7], [51,60,75,18], [1,2,3,4]]
print(f"Python List Dimention : {np.ndim(new_list)}")

np_list2 = np.array(new_list, ndmin=3)
print(f"Increased Dimention   : {np_list2.ndim}")

Python List Dimention : 2
Increased Dimention   : 3


## __3. np.shape__

_numpy.shape()_ is a function in the NumPy library for Python that returns the shape of an array. The shape of an array refers to the number of elements along each dimension of the array.

In [4]:
print(np_list2, "\n")
print(f"Shape of 'np_list2': {np_list2.shape}")

[[[15  5  3  7]
  [51 60 75 18]
  [ 1  2  3  4]]] 

Shape of 'np_list2': (1, 3, 4)


## __4. np.reshape()__

The _np.reshape()_ function is a fundamental tool in the NumPy library for manipulating the shape of arrays. It allows you to change the dimensions of an array without altering its underlying data.

In [5]:
normal_list = [15, 5, 3, 7, 51, 60, 75, 18, 1, 2, 3, 4]

#### __(Row, Column)__

In [6]:
my_reshape = normal_list
print(np.array(normal_list).reshape(6,2), "\n")      # 1st Row | 2nd Column

print(f"Shape of Array: {np.array(normal_list).reshape(6,2).shape}")

[[15  5]
 [ 3  7]
 [51 60]
 [75 18]
 [ 1  2]
 [ 3  4]] 

Shape of Array: (6, 2)


#### __(Dimention, Row, Column)__

In [7]:
my_reshape = normal_list
print(np.array(normal_list).reshape(2,2,3), "\n")     # 1st Dimention | 2nd Row | 3rd Column
print(f"Shape of Array: {np.array(normal_list).reshape(2,2,3).shape}")

[[[15  5  3]
  [ 7 51 60]]

 [[75 18  1]
  [ 2  3  4]]] 

Shape of Array: (2, 2, 3)


In [8]:
my_reshape = normal_list
print(np.array(normal_list).reshape(1,1,2,3,2), "\n")  # 1st Dimention (1,1,2) | 4th Row | 5th Column
print(f"Shape of Array: {np.array(normal_list).reshape(1,1,2,3,2).shape}")

[[[[[15  5]
    [ 3  7]
    [51 60]]

   [[75 18]
    [ 1  2]
    [ 3  4]]]]] 

Shape of Array: (1, 1, 2, 3, 2)


## __5. np.nditer()__

It is an efficient, multi-dimensional iterator object in NumPy designed to iterate over arrays.

In [9]:
new_list = [[15,5,3,7], [51,60,75,18], [1,2,3,4]]

np_list = np.array(new_list)

print(f"{'*'*10} Joined {'*'*10}")
for x in np.nditer(np_list):
    print(x, end=" ")

********** Joined **********
15 5 3 7 51 60 75 18 1 2 3 4 

## __6. np.ndenumerate()__

It is a function in NumPy that provides an iterator yielding pairs of array coordinates (indices) and the corresponding values for each element in an N-dimensional array.

In [10]:
new_list = [[15,5,3,7], [51,60,75,18], [1,2,3,4]]

np_list = np.array(new_list)

print(f"{'*'*10} 2D Array {'*'*10}")
print(np_list, "\n")

for x in np.ndenumerate(np.nditer(np_list)):
    print(x)

********** 2D Array **********
[[15  5  3  7]
 [51 60 75 18]
 [ 1  2  3  4]] 

((0,), np.int64(15))
((1,), np.int64(5))
((2,), np.int64(3))
((3,), np.int64(7))
((4,), np.int64(51))
((5,), np.int64(60))
((6,), np.int64(75))
((7,), np.int64(18))
((8,), np.int64(1))
((9,), np.int64(2))
((10,), np.int64(3))
((11,), np.int64(4))


In [11]:
print(f"{'*'*10} 3D Array {'*'*10}")
print(np_list2, "\n")
for x in np.ndenumerate(np_list2):
    print(x)

********** 3D Array **********
[[[15  5  3  7]
  [51 60 75 18]
  [ 1  2  3  4]]] 

((0, 0, 0), np.int64(15))
((0, 0, 1), np.int64(5))
((0, 0, 2), np.int64(3))
((0, 0, 3), np.int64(7))
((0, 1, 0), np.int64(51))
((0, 1, 1), np.int64(60))
((0, 1, 2), np.int64(75))
((0, 1, 3), np.int64(18))
((0, 2, 0), np.int64(1))
((0, 2, 1), np.int64(2))
((0, 2, 2), np.int64(3))
((0, 2, 3), np.int64(4))


In [12]:
print(f"{'*'*10} 5D Array {'*'*10}\n")

for x in np.ndenumerate(np.array(normal_list).reshape(1,1,2,3,2)):
    print(x)
print()
print(f"Total Dimentions: {np.ndim(np.array(normal_list).reshape(1,1,2,3,2))}")

********** 5D Array **********

((0, 0, 0, 0, 0), np.int64(15))
((0, 0, 0, 0, 1), np.int64(5))
((0, 0, 0, 1, 0), np.int64(3))
((0, 0, 0, 1, 1), np.int64(7))
((0, 0, 0, 2, 0), np.int64(51))
((0, 0, 0, 2, 1), np.int64(60))
((0, 0, 1, 0, 0), np.int64(75))
((0, 0, 1, 0, 1), np.int64(18))
((0, 0, 1, 1, 0), np.int64(1))
((0, 0, 1, 1, 1), np.int64(2))
((0, 0, 1, 2, 0), np.int64(3))
((0, 0, 1, 2, 1), np.int64(4))

Total Dimentions: 5


## __7. array.flatten()__

The _flatten()_ method in NumPy is used to convert a multi-dimensional NumPy array into a one-dimensional array.

#### __Parameters:__

- order ({'C', 'F', 'A', 'K'}) Optional

    - 'C' (default): Flatten in row-major (C-style) order.
    - 'F': Flatten in column-major (Fortran-style) order.
    - 'A': Flatten in column-major order if the array is Fortran contiguous in memory, row-major order otherwise.
    - 'K': Flatten in the order the elements occur in memory. 

#### __Example:__

__7.1 Order = 'C'__ _Default_

In [13]:
flatten = np_list2.flatten()
flatten

array([15,  5,  3,  7, 51, 60, 75, 18,  1,  2,  3,  4])

__7.2 Order = 'F'__

In [14]:
flatten = np_list2.flatten(order="F")
flatten

array([15, 51,  1,  5, 60,  2,  3, 75,  3,  7, 18,  4])

## __8. array.size__

- The _.size_ attribute of a NumPy array _(ndarray)_ returns the total number of elements in the array.

In [15]:
print(f"Array Size: {flatten.size}")

Array Size: 12


## __9. array.tolist()__

The _tolist()_ method in NumPy is used to convert a NumPy array _(ndarray)_ into a standard Python list.

In [16]:
normal_python_list = flatten.tolist()      # list
print(type(normal_python_list))
normal_python_list

<class 'list'>


[15, 51, 1, 5, 60, 2, 3, 75, 3, 7, 18, 4]

## __10. stack__

- _np.stack()_ is a NumPy function used to join a sequence of arrays along a new axis.
- Resulting stacked array will have one more dimension than the input arrays.

#### __Example:__

In [17]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

### __10.1 np.stack__

__10.1.1 Axis 0 (Default )__

- _np.stack_ with axis=0 joins a sequence of arrays along a new axis at the beginning (index 0) of the resulting array's dimensions.

In [18]:
stack0 = np.stack((arr1, arr2))
stack0

array([[1, 2, 3],
       [4, 5, 6]])

__10.1.2 Axis 1__

- _np.stack()_ with axis=1 it means the new axis will be inserted at index 1 in the resulting array's dimensions.

In [19]:
stack1 = np.stack((arr1, arr2), axis=1)
stack1

array([[1, 4],
       [2, 5],
       [3, 6]])

### __10.2 np.hstack__

- _np.hstack_ stands for horizontal stack.
- _np.hstack()_ is a function in the NumPy library used to stack arrays in sequence horizontally (column-wise).

In [20]:
hstack = np.hstack((arr1, arr2))
print(f"Dimention is: {np.ndim(hstack)}")
hstack

Dimention is: 1


array([1, 2, 3, 4, 5, 6])

### __10.3 np.dstack__

- _np.dstack_ stands for depth-wise stack.
- _np.dstack()_ is a function in the NumPy library used to stack arrays in sequence depth-wise, meaning along the third axis (axis=2).

In [21]:
dstack = np.dstack((arr1, arr2))
print(f"Dimention is: {np.ndim(dstack)}")
dstack

Dimention is: 3


array([[[1, 4],
        [2, 5],
        [3, 6]]])