# Numpy - Linear Algebra

In [1]:
import numpy as np

### Polynomial Equations:

2x + 3y = 10

4x + 5y = 20

In [3]:
eq , val = [[2,3], [4,5]], [10,20]

np.linalg.solve(eq,val)

array([5., 0.])

2x+5y+6z = 10

5x+6y+8z = 20

7x+8y+10z = 30

In [4]:
eq1, val1 = [[2,5,6], [5,6,8], [7,8,10]], [10,20,30]
np.linalg.solve(eq1, val1)

array([ 4.,  4., -3.])

# Representation of Polynomial Equation

In [9]:
r_eq = np.polynomial.Polynomial(eq[1])
r_eq

Polynomial([4., 5.], domain=[-1.,  1.], window=[-1.,  1.], symbol='x')

In [10]:
r_eq.roots()

array([-0.8])

In [12]:
# 2x**2 + 3x + 6 = 0
new_eq = [6, 3, 2]
new_eq_1 = np.polynomial.Polynomial(new_eq)
print(new_eq_1)
print(f"Root: {new_eq_1.roots()}")

6.0 + 3.0 x + 2.0 x**2
Root: [-0.75-1.5612495j -0.75+1.5612495j]


In [18]:
np.sqrt(39)/4

np.float64(1.5612494995995996)

# Eigen values and eigen vectors

[2,
 3]

[4,
 5]

In [28]:
np.linalg.eigvals([[2,4], [4,5]])

array([-0.77200187,  7.77200187])

In [37]:
np.linalg.eigvals([[1,2], [5,4]])

array([-1.,  6.])

[1  2]
[5  4]

1-(-1)  2
5       4-(-1)

2       2
5       5

# Eigen Values Formula

(1-λ) ⨉ (4-λ) - (2 ⨉ 5) = 0

⇒ 4 - λ - 4λ + λ2 - 10 = 0

⇒ λ2 - 5λ - 6 = 0

⇒ λ2 - (6λ - λ) - 6 = 0

⇒ λ2 - 6λ + λ - 6 = 0

⇒ (λ-6)(λ+1) = 0

λ = 6 and λ = -1

In [43]:
np.linalg.eigvals([[2,4], [4,5]])

np.linalg.eig([[1,2], [5,4]])

EigResult(eigenvalues=array([-1.,  6.]), eigenvectors=array([[-0.70710678, -0.37139068],
       [ 0.70710678, -0.92847669]]))

# Eigen Vector Formula

Simplifying the above determinant we get

⇒ (2-λ)(λ2) + 2λ2 + 2λ2 = 0   ⇒ (-λ3) + 6λ2 = 0  

⇒ λ2(6 - λ) = 0

⇒ λ = 0, λ = 6, λ = 0

# deteminant

a * d - b*c

In [45]:
a, b = [2,4], [4,5]
np.linalg.det([a,b])

np.float64(-6.0)

In [48]:
2*5 - 4*4

-6