# __Accessing Data__

In [1]:
import pandas as pd
import numpy as np

## __1. Access Items__

In [2]:
emp_data = pd.read_csv("data/Emp_data.csv")
df = pd.DataFrame(emp_data)

In [3]:
df

Emp ID First Name  Age in Yrs  Weight in Kgs  Age in Company  Salary  \
0   677509       Lois       36.36             60           13.68  168251   
1   940761     Brenda       47.02             60            9.01   51063   
2   428945        Joe       54.15             68            0.98   50155   
3   408351      Diane       39.67             51           18.30  180294   
4   193819   Benjamin       40.31             58            4.01  117642   
..     ...        ...         ...            ...             ...     ...   
95  639892       Jose       22.82             89            1.05  129774   
96  704709     Harold       32.61             77            5.93  156194   
97  461593     Nicole       52.66             60           28.53   95673   
98  392491    Theresa       29.60             57            6.99   51015   
99  495141      Tammy       38.38             55            2.26   93650   

            City  
0         Denver  
1      Stonewall  
2   Michigantown  
3       Hydetown  
4        Fremont  
..           ...  
95        Biloxi  
96  Carol Stream  
97       Detroit  
98      Mc Grath  
99          Alma  

[100 rows x 7 columns]

### __1.1 df['column_name']__

In [4]:
df['Emp ID']

0     677509
1     940761
2     428945
3     408351
4     193819
       ...  
95    639892
96    704709
97    461593
98    392491
99    495141
Name: Emp ID, Length: 100, dtype: int64

### __1.2 df.column_name__

In [5]:
df.Salary

0     168251
1      51063
2      50155
3     180294
4     117642
       ...  
95    129774
96    156194
97     95673
98     51015
99     93650
Name: Salary, Length: 100, dtype: int64

### __1.3 df[['Col1', 'Col2', ...,'ColN']]__

In [6]:
df[['First Name', 'Age in Company']]

First Name  Age in Company
0        Lois           13.68
1      Brenda            9.01
2         Joe            0.98
3       Diane           18.30
4    Benjamin            4.01
..        ...             ...
95       Jose            1.05
96     Harold            5.93
97     Nicole           28.53
98    Theresa            6.99
99      Tammy            2.26

[100 rows x 2 columns]

## __2. df.iloc__

### __2.1 df.iloc[start_row_index : end_row_index ]__

In [7]:
df.iloc[2:5]

Emp ID First Name  Age in Yrs  Weight in Kgs  Age in Company  Salary  \
2  428945        Joe       54.15             68            0.98   50155   
3  408351      Diane       39.67             51           18.30  180294   
4  193819   Benjamin       40.31             58            4.01  117642   

           City  
2  Michigantown  
3      Hydetown  
4       Fremont

### __2.2 df.iloc[row_index_list]__

In [8]:
df.iloc[[0,3,6]]

Emp ID First Name  Age in Yrs  Weight in Kgs  Age in Company  Salary  \
0  677509       Lois       36.36             60           13.68  168251   
3  408351      Diane       39.67             51           18.30  180294   
6  539712      Nancy       22.14             50            0.87   98189   

       City  
0    Denver  
3  Hydetown  
6   Atlanta

### __2.3 df.iloc[row_index_list, col_index_list]__

In [9]:
df.iloc[[0,3,6], [0,2,3,4,5]]

Emp ID  Age in Yrs  Weight in Kgs  Age in Company  Salary
0  677509       36.36             60           13.68  168251
3  408351       39.67             51           18.30  180294
6  539712       22.14             50            0.87   98189

### __2.4 df.iloc[:, col_index_list]__

In [10]:
df.iloc[:, [0,1,6]]

Emp ID First Name          City
0   677509       Lois        Denver
1   940761     Brenda     Stonewall
2   428945        Joe  Michigantown
3   408351      Diane      Hydetown
4   193819   Benjamin       Fremont
..     ...        ...           ...
95  639892       Jose        Biloxi
96  704709     Harold  Carol Stream
97  461593     Nicole       Detroit
98  392491    Theresa      Mc Grath
99  495141      Tammy          Alma

[100 rows x 3 columns]

## __3. df.loc__

### __3.1 df.loc['row_labels', 'col_labels']__

In [11]:
df.loc[[0,77,88,99], ['Emp ID', 'First Name', 'City']]

Emp ID First Name           City
0   677509       Lois         Denver
77  870820     Martha         Nardin
88  844177   Margaret  Richmond Dale
99  495141      Tammy           Alma

## __4. df.head()__

In [12]:
# default is 5

df.head()

Emp ID First Name  Age in Yrs  Weight in Kgs  Age in Company  Salary  \
0  677509       Lois       36.36             60           13.68  168251   
1  940761     Brenda       47.02             60            9.01   51063   
2  428945        Joe       54.15             68            0.98   50155   
3  408351      Diane       39.67             51           18.30  180294   
4  193819   Benjamin       40.31             58            4.01  117642   

           City  
0        Denver  
1     Stonewall  
2  Michigantown  
3      Hydetown  
4       Fremont

## __5. df.tail()__

In [13]:
# default is 5

df.tail()

Emp ID First Name  Age in Yrs  Weight in Kgs  Age in Company  Salary  \
95  639892       Jose       22.82             89            1.05  129774   
96  704709     Harold       32.61             77            5.93  156194   
97  461593     Nicole       52.66             60           28.53   95673   
98  392491    Theresa       29.60             57            6.99   51015   
99  495141      Tammy       38.38             55            2.26   93650   

            City  
95        Biloxi  
96  Carol Stream  
97       Detroit  
98      Mc Grath  
99          Alma

## __6. Access items by using for loop:__

### __6.1. df.items()__

In [14]:
for col, val in df.items():
    print(f"Column Name: {col}\n{'-'*40}\n{val}\n{'-'*40}")

Column Name: Emp ID
----------------------------------------
0     677509
1     940761
2     428945
3     408351
4     193819
       ...  
95    639892
96    704709
97    461593
98    392491
99    495141
Name: Emp ID, Length: 100, dtype: int64
----------------------------------------
Column Name: First Name
----------------------------------------
0         Lois
1       Brenda
2          Joe
3        Diane
4     Benjamin
        ...   
95        Jose
96      Harold
97      Nicole
98     Theresa
99       Tammy
Name: First Name, Length: 100, dtype: object
----------------------------------------
Column Name: Age in Yrs
----------------------------------------
0     36.36
1     47.02
2     54.15
3     39.67
4     40.31
      ...  
95    22.82
96    32.61
97    52.66
98    29.60
99    38.38
Name: Age in Yrs, Length: 100, dtype: float64
----------------------------------------
Column Name: Weight in Kgs
----------------------------------------
0     60
1     60
2     68
3     51
4     58
  

### __6.2. df.iterrows()__

In [15]:
for row, val in df.iterrows():
    print(f"Row Name: {row}\n{'-'*40}\n{val}\n{'-'*40}")

Row Name: 0
----------------------------------------
Emp ID            677509
First Name          Lois
Age in Yrs         36.36
Weight in Kgs         60
Age in Company     13.68
Salary            168251
City              Denver
Name: 0, dtype: object
----------------------------------------
Row Name: 1
----------------------------------------
Emp ID               940761
First Name           Brenda
Age in Yrs            47.02
Weight in Kgs            60
Age in Company         9.01
Salary                51063
City              Stonewall
Name: 1, dtype: object
----------------------------------------
Row Name: 2
----------------------------------------
Emp ID                  428945
First Name                 Joe
Age in Yrs               54.15
Weight in Kgs               68
Age in Company            0.98
Salary                   50155
City              Michigantown
Name: 2, dtype: object
----------------------------------------
Row Name: 3
----------------------------------------
Emp ID  

## __7. Df to Numpy:__ 

In [16]:
df.head(1)

Emp ID First Name  Age in Yrs  Weight in Kgs  Age in Company  Salary  \
0  677509       Lois       36.36             60           13.68  168251   

     City  
0  Denver

### __7.1. df.to_numpy()__

In [17]:
df.iloc[:, [0,2,3,4,5]].to_numpy()

array([[6.77509e+05, 3.63600e+01, 6.00000e+01, 1.36800e+01, 1.68251e+05],
       [9.40761e+05, 4.70200e+01, 6.00000e+01, 9.01000e+00, 5.10630e+04],
       [4.28945e+05, 5.41500e+01, 6.80000e+01, 9.80000e-01, 5.01550e+04],
       [4.08351e+05, 3.96700e+01, 5.10000e+01, 1.83000e+01, 1.80294e+05],
       [1.93819e+05, 4.03100e+01, 5.80000e+01, 4.01000e+00, 1.17642e+05],
       [4.99687e+05, 3.48600e+01, 5.80000e+01, 1.20200e+01, 7.23050e+04],
       [5.39712e+05, 2.21400e+01, 5.00000e+01, 8.70000e-01, 9.81890e+04],
       [3.80086e+05, 5.91200e+01, 4.00000e+01, 3.45200e+01, 6.09180e+04],
       [4.77616e+05, 5.81800e+01, 4.20000e+01, 2.32700e+01, 1.21587e+05],
       [1.62402e+05, 2.97300e+01, 6.00000e+01, 3.44000e+00, 4.30100e+04],
       [2.31469e+05, 4.25000e+01, 8.00000e+01, 8.29000e+00, 1.18457e+05],
       [1.53989e+05, 2.22100e+01, 6.10000e+01, 5.60000e-01, 8.29650e+04],
       [3.86158e+05, 4.54500e+01, 5.50000e+01, 1.68000e+00, 1.66892e+05],
       [3.01576e+05, 2.11000e+01, 8.70

### __7.2. df.values__

In [18]:
df.iloc[:, [0,2,3,4,5]].values

array([[6.77509e+05, 3.63600e+01, 6.00000e+01, 1.36800e+01, 1.68251e+05],
       [9.40761e+05, 4.70200e+01, 6.00000e+01, 9.01000e+00, 5.10630e+04],
       [4.28945e+05, 5.41500e+01, 6.80000e+01, 9.80000e-01, 5.01550e+04],
       [4.08351e+05, 3.96700e+01, 5.10000e+01, 1.83000e+01, 1.80294e+05],
       [1.93819e+05, 4.03100e+01, 5.80000e+01, 4.01000e+00, 1.17642e+05],
       [4.99687e+05, 3.48600e+01, 5.80000e+01, 1.20200e+01, 7.23050e+04],
       [5.39712e+05, 2.21400e+01, 5.00000e+01, 8.70000e-01, 9.81890e+04],
       [3.80086e+05, 5.91200e+01, 4.00000e+01, 3.45200e+01, 6.09180e+04],
       [4.77616e+05, 5.81800e+01, 4.20000e+01, 2.32700e+01, 1.21587e+05],
       [1.62402e+05, 2.97300e+01, 6.00000e+01, 3.44000e+00, 4.30100e+04],
       [2.31469e+05, 4.25000e+01, 8.00000e+01, 8.29000e+00, 1.18457e+05],
       [1.53989e+05, 2.22100e+01, 6.10000e+01, 5.60000e-01, 8.29650e+04],
       [3.86158e+05, 4.54500e+01, 5.50000e+01, 1.68000e+00, 1.66892e+05],
       [3.01576e+05, 2.11000e+01, 8.70

# __8. Series to numpy:__

In [19]:
df["Age in Yrs"].to_numpy()

array([36.36, 47.02, 54.15, 39.67, 40.31, 34.86, 22.14, 59.12, 58.18,
       29.73, 42.5 , 22.21, 45.45, 21.1 , 59.47, 50.97, 47.23, 24.66,
       58.08, 49.85, 22.64, 23.77, 44.72, 37.27, 59.42, 28.02, 27.59,
       48.09, 42.39, 53.68, 36.24, 36.14, 23.92, 26.24, 24.02, 49.69,
       48.49, 33.89, 43.63, 55.97, 55.14, 35.02, 32.58, 38.65, 52.99,
       33.73, 27.73, 56.38, 23.73, 21.3 , 28.76, 28.23, 58.15, 34.75,
       56.66, 26.25, 24.61, 59.27, 56.27, 21.93, 56.53, 47.78, 32.75,
       22.72, 25.93, 57.37, 32.08, 52.51, 30.9 , 34.87, 43.59, 54.16,
       25.1 , 31.29, 58.43, 25.96, 32.29, 26.35, 50.05, 41.19, 48.79,
       25.98, 32.77, 33.55, 24.01, 42.79, 42.21, 50.7 , 35.91, 37.62,
       37.84, 39.77, 37.57, 56.  , 39.43, 22.82, 32.61, 52.66, 29.6 ,
       38.38])

In [20]:
df["Age in Yrs"].values

array([36.36, 47.02, 54.15, 39.67, 40.31, 34.86, 22.14, 59.12, 58.18,
       29.73, 42.5 , 22.21, 45.45, 21.1 , 59.47, 50.97, 47.23, 24.66,
       58.08, 49.85, 22.64, 23.77, 44.72, 37.27, 59.42, 28.02, 27.59,
       48.09, 42.39, 53.68, 36.24, 36.14, 23.92, 26.24, 24.02, 49.69,
       48.49, 33.89, 43.63, 55.97, 55.14, 35.02, 32.58, 38.65, 52.99,
       33.73, 27.73, 56.38, 23.73, 21.3 , 28.76, 28.23, 58.15, 34.75,
       56.66, 26.25, 24.61, 59.27, 56.27, 21.93, 56.53, 47.78, 32.75,
       22.72, 25.93, 57.37, 32.08, 52.51, 30.9 , 34.87, 43.59, 54.16,
       25.1 , 31.29, 58.43, 25.96, 32.29, 26.35, 50.05, 41.19, 48.79,
       25.98, 32.77, 33.55, 24.01, 42.79, 42.21, 50.7 , 35.91, 37.62,
       37.84, 39.77, 37.57, 56.  , 39.43, 22.82, 32.61, 52.66, 29.6 ,
       38.38])

# __9. DataFrame to list:__

In [21]:
df.head(10).to_numpy().tolist()

[[677509, 'Lois', 36.36, 60, 13.68, 168251, 'Denver'],
 [940761, 'Brenda', 47.02, 60, 9.01, 51063, 'Stonewall'],
 [428945, 'Joe', 54.15, 68, 0.98, 50155, 'Michigantown'],
 [408351, 'Diane', 39.67, 51, 18.3, 180294, 'Hydetown'],
 [193819, 'Benjamin', 40.31, 58, 4.01, 117642, 'Fremont'],
 [499687, 'Patrick', 34.86, 58, 12.02, 72305, 'Macksburg'],
 [539712, 'Nancy', 22.14, 50, 0.87, 98189, 'Atlanta'],
 [380086, 'Carol', 59.12, 40, 34.52, 60918, 'Blanchester'],
 [477616, 'Frances', 58.18, 42, 23.27, 121587, 'Delmita'],
 [162402, 'Diana', 29.73, 60, 3.44, 43010, 'Eureka Springs']]

# __10. Series to list:__

In [22]:
df["Age in Yrs"].head(10).to_numpy().tolist()

[36.36, 47.02, 54.15, 39.67, 40.31, 34.86, 22.14, 59.12, 58.18, 29.73]

# __11. Sorting:__

### __11.1. df.sort_index(axis = 0, inplace = True)__

In [23]:
df.sort_index(axis = 0)

Emp ID First Name  Age in Yrs  Weight in Kgs  Age in Company  Salary  \
0   677509       Lois       36.36             60           13.68  168251   
1   940761     Brenda       47.02             60            9.01   51063   
2   428945        Joe       54.15             68            0.98   50155   
3   408351      Diane       39.67             51           18.30  180294   
4   193819   Benjamin       40.31             58            4.01  117642   
..     ...        ...         ...            ...             ...     ...   
95  639892       Jose       22.82             89            1.05  129774   
96  704709     Harold       32.61             77            5.93  156194   
97  461593     Nicole       52.66             60           28.53   95673   
98  392491    Theresa       29.60             57            6.99   51015   
99  495141      Tammy       38.38             55            2.26   93650   

            City  
0         Denver  
1      Stonewall  
2   Michigantown  
3       Hydetown  
4        Fremont  
..           ...  
95        Biloxi  
96  Carol Stream  
97       Detroit  
98      Mc Grath  
99          Alma  

[100 rows x 7 columns]

### __11.2. df.reset_index()__

In [24]:
print("Reset Index:")
df.reset_index()

Reset Index:


index  Emp ID First Name  Age in Yrs  Weight in Kgs  Age in Company  \
0       0  677509       Lois       36.36             60           13.68   
1       1  940761     Brenda       47.02             60            9.01   
2       2  428945        Joe       54.15             68            0.98   
3       3  408351      Diane       39.67             51           18.30   
4       4  193819   Benjamin       40.31             58            4.01   
..    ...     ...        ...         ...            ...             ...   
95     95  639892       Jose       22.82             89            1.05   
96     96  704709     Harold       32.61             77            5.93   
97     97  461593     Nicole       52.66             60           28.53   
98     98  392491    Theresa       29.60             57            6.99   
99     99  495141      Tammy       38.38             55            2.26   

    Salary          City  
0   168251        Denver  
1    51063     Stonewall  
2    50155  Michigantown  
3   180294      Hydetown  
4   117642       Fremont  
..     ...           ...  
95  129774        Biloxi  
96  156194  Carol Stream  
97   95673       Detroit  
98   51015      Mc Grath  
99   93650          Alma  

[100 rows x 8 columns]

### __11.3. df.reset_index(drop = True)__

In [25]:
print("Droppind Reset Index:")
df.reset_index(drop=True)

Droppind Reset Index:


Emp ID First Name  Age in Yrs  Weight in Kgs  Age in Company  Salary  \
0   677509       Lois       36.36             60           13.68  168251   
1   940761     Brenda       47.02             60            9.01   51063   
2   428945        Joe       54.15             68            0.98   50155   
3   408351      Diane       39.67             51           18.30  180294   
4   193819   Benjamin       40.31             58            4.01  117642   
..     ...        ...         ...            ...             ...     ...   
95  639892       Jose       22.82             89            1.05  129774   
96  704709     Harold       32.61             77            5.93  156194   
97  461593     Nicole       52.66             60           28.53   95673   
98  392491    Theresa       29.60             57            6.99   51015   
99  495141      Tammy       38.38             55            2.26   93650   

            City  
0         Denver  
1      Stonewall  
2   Michigantown  
3       Hydetown  
4        Fremont  
..           ...  
95        Biloxi  
96  Carol Stream  
97       Detroit  
98      Mc Grath  
99          Alma  

[100 rows x 7 columns]

### __11.4. df.sort_values('column_name', ascending = True)__

In [26]:
df.sort_values('Weight in Kgs', ascending = True)

Emp ID First Name  Age in Yrs  Weight in Kgs  Age in Company  Salary  \
7   380086      Carol       59.12             40           34.52   60918   
47  524896       Judy       56.38             40            5.59  133332   
41  227922     Amanda       35.02             40           10.28  114257   
75  765850      Linda       25.96             40            0.20  113256   
29  335732     Brenda       53.68             41           29.96   60508   
..     ...        ...         ...            ...             ...     ...   
13  301576      Wayne       21.10             87            0.02   92758   
87  623929      Jimmy       50.70             87            9.63  120631   
82  761821     Ernest       32.77             87            2.49  176675   
95  639892       Jose       22.82             89            1.05  129774   
38  726264       Carl       43.63             90           10.14  162159   

            City  
7    Blanchester  
47        Topeka  
41  Lake Charles  
75        Albion  
29          Mesa  
..           ...  
13         Maida  
87      Oriskany  
82  Saranac Lake  
95        Biloxi  
38        Wright  

[100 rows x 7 columns]

### __11.5. df.sort_values(['column_name1', 'column_name2'], ascending = True)__

In [27]:
df.sort_values(['Salary', 'Emp ID'], ascending = True)

Emp ID   First Name  Age in Yrs  Weight in Kgs  Age in Company  Salary  \
24  560455      Carolyn       59.42             53           16.08   42005   
9   162402        Diana       29.73             60            3.44   43010   
72  951225     Margaret       25.10             56            0.92   43867   
60  687017      Frances       56.53             42            6.94   46945   
79  325319      Carolyn       41.19             60            2.73   48736   
..     ...          ...         ...            ...             ...     ...   
71  478003      Cynthia       54.16             60           13.41  186200   
42  265813         Jack       32.58             50           10.01  186280   
55  253573       Sharon       26.25             43            3.39  190139   
65  917395  Christopher       57.37             62           19.73  190765   
17  214352      Theresa       24.66             59            2.52  197537   

              City  
24     Saint Cloud  
9   Eureka Springs  
72         Haswell  
60           Trego  
79         Wheaton  
..             ...  
71     Kansas City  
42        Kalvesta  
55         Bartley  
65    Willow Beach  
17     Toeterville  

[100 rows x 7 columns]

### __11.6. series.sort_values()__

In [28]:
df["Age in Company"].sort_values()

13     0.02
80     0.07
62     0.10
49     0.13
75     0.20
      ...  
14    26.69
97    28.53
29    29.96
93    34.32
7     34.52
Name: Age in Company, Length: 100, dtype: float64